import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations = {
  en: {
    home: 'Home',
    events: 'Events',
    about: 'About',
    donate: 'Donate',
    volunteer: 'Volunteer',
    dashboard: 'Dashboard',
    login: 'Login',
    logout: 'Log out',
    toggleHighContrast: 'Toggle High Contrast',
    toggleLargerText: 'Toggle Larger Text',
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    kannada: 'Kannada',
    upcomingEvents: 'Upcoming Events',
    loadingEvents: 'Loading events...',
    failedToLoadEvents: 'Failed to load events. Please try again later.',
    showMore: 'Show More',
    livesImpacted: 'Lives Impacted',
    eventsOrganized: 'Events Organized',
    volunteersEngaged: 'Volunteers Engaged',
    yearsOfService: 'Years of Service',
    aboutUs: 'About Us',
    breakingBarriers: 'Breaking Barriers for Inclusive Growth',
    aboutDescription1: 'Founded in 1997, Samarthanam Trust has been at the forefront of empowering persons with disabilities through various initiatives in education, livelihood, sports, rehabilitation, and cultural activities.',
    aboutDescription2: 'Our technology-driven approach ensures that we can provide the right tools and resources to help individuals overcome barriers and achieve their full potential.',
    learnMore: 'Learn More About Us',
    communityActivitiesAlt: 'Samarthanam Trust community activities',
    heroTitle: 'Empowering Lives Through Inclusive Technology',
    heroSubtitle: 'Join Samarthanam Trust in our mission to support visually impaired, disabled, and underprivileged individuals through accessibility, education, and community.',
    becomeVolunteer: 'Become a Volunteer',
    browseEvents: 'Browse Events',
    scrollDown: 'Scroll down',
    footerDescription: 'Empowering visually impaired, disabled, and underprivileged individuals through technology and community support.',
    facebook: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    youtube: 'YouTube',
    quickLinks: 'Quick Links',
    contact: 'Contact',
    address: 'CA Site No.1, 7th Main, 7th Cross, 3rd Phase, JP Nagar, Bengaluru, Karnataka 560078',
    stayUpdated: 'Stay Updated',
    newsletterDescription: 'Subscribe to our newsletter for updates on events, volunteer opportunities, and more.',
    yourEmail: 'Your email',
    subscribe: 'Subscribe',
    enterValidEmail: 'Please enter a valid email address.',
    subscriptionFailed: 'Subscription failed. Try again later.',
    subscribedSuccessfully: 'Subscribed successfully!',
    copyright: '© {{year}} Samarthanam Trust for the Disabled. All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    recommended: 'Recommended',
    alreadySignedUp: 'Already Signed Up',
    signingUp: 'Signing Up...',
    volunteerForEvent: 'Volunteer for Event',
    registerAsParticipant: 'Register as Participant',
    aboutTitle: 'About Samarthanam Trust',
    aboutSubtitle: 'Founded in 1997, Samarthanam Trust has been dedicated to empowering people with disabilities through education, employment, and inclusion.',
    ourPurpose: 'Our Purpose',
    missionVision: 'Mission & Vision',
    missionVisionDescription: 'We envision a world where all persons with disabilities have equal opportunities to education, employment, and social inclusion, enabling them to live with dignity and independence.',
    education: 'Education',
    educationDescription: 'Provide quality education and training to people with disabilities and from underprivileged backgrounds.',
    employment: 'Employment',
    employmentDescription: 'Create meaningful employment opportunities through skill development and partnerships with industries.',
    inclusion: 'Inclusion',
    inclusionDescription: 'Promote inclusion in all aspects of society, ensuring equal participation for all individuals.',
    awareness: 'Awareness',
    awarenessDescription: 'Increase public awareness about disabilities and advocate for supportive policies and infrastructure.',
    ourJourney: 'Our Journey',
    milestonesAchievements: 'Milestones & Achievements',
    milestonesDescription: 'From our humble beginnings to our present impact, we have been driven by our commitment to create a more inclusive world for all.',
    foundation: 'Foundation',
    foundationDescription: 'Samarthanam Trust was founded with a vision to provide support to persons with disabilities and from underprivileged backgrounds.',
    educationCenter: 'Education Center',
    educationCenterDescription: 'Established our first dedicated education center with accessible infrastructure and learning materials.',
    digitalAccess: 'Digital Access',
    digitalAccessDescription: 'Launched digital literacy programs specifically designed for visually impaired individuals.',
    nationalExpansion: 'National Expansion',
    nationalExpansionDescription: 'Expanded operations to five states across India, reaching thousands more beneficiaries.',
    globalRecognition: 'Global Recognition',
    globalRecognitionDescription: 'Received international recognition for our work in disability inclusion and accessibility innovation.',
    present: 'Present',
    embracingTechnology: 'Embracing Technology',
    embracingTechnologyDescription: 'Leveraging advanced technology to create more accessible solutions and reach wider communities.',
    ourImpact: 'Our Impact',
    makingDifference: 'Making a Difference',
    impactDescription: 'Our work has touched thousands of lives across the country, creating lasting positive change for individuals with disabilities and their communities.',
    communityImpactAlt: 'Samarthanam community impact',
    empoweringLives: 'Empowering Lives',
    empoweringLivesDescription: 'We have provided education and skill development to over 20,000 individuals with disabilities, helping them achieve independence and dignity.',
    creatingOpportunities: 'Creating Opportunities',
    creatingOpportunitiesDescription: 'Our partnerships with 200+ companies have created employment opportunities for thousands of persons with disabilities in diverse sectors.',
    communityEngagement: 'Community Engagement',
    communityEngagementDescription: 'Through 500+ events and workshops, we\'ve raised awareness about disability inclusion and built supportive communities across the country.',
    recognition: 'Recognition',
    recognitionDescription: 'Our work has been recognized with numerous national and international awards for excellence in disability empowerment and inclusion.',
    ourTeam: 'Our Team',
    leadership: 'Leadership',
    leadershipDescription: 'Meet the dedicated team leading Samarthanam\'s mission to create a more inclusive world.',
    mahanteshName: 'Mahantesh G Kivadasannavar',
    mahanteshPosition: 'Founder & Managing Trustee',
    supriyaName: 'Supriya Purwar',
    supriyaPosition: 'Executive Director',
    rameshName: 'Ramesh Kumar',
    rameshPosition: 'Director of Programs',
    priyaName: 'Priya Sharma',
    priyaPosition: 'Technology Officer',
    donationTitle: 'Make a Donation to Samarthanam Trust',
    donationSubtitle: 'Your contribution helps us empower persons with disabilities through education, skill development, and inclusive programs.',
    taxExemptionInfo: 'All donations to Samarthanam Trust are eligible for tax exemption under Section 80G in India.',
    donationDetails: 'Your Donation Details',
    donationDetailsDescription: 'Please fill in the details to complete your donation',
    donationType: 'Donation Type',
    oneTimeDonation: 'One-time Donation',
    monthlyDonation: 'Monthly Donation',
    oneTimeDonationDescription: 'Make a one-time donation to support our programs.',
    monthlyDonationDescription: 'Your monthly donation helps us plan and sustain our programs.',
    donationAmount: 'Donation Amount (₹)',
    custom: 'Custom',
    enterAmount: 'Enter Amount',
    enterAmountPlaceholder: 'Enter amount',
    donationPurpose: 'Choose Donation Purpose',
    donationEducation: 'Education',
    donationSkill: 'Skill Development',
    donationLivelihood: 'Livelihood',
    donationSports: 'Sports',
    donationCultural: 'Cultural Programs',
    donationGeneral: 'General Donation',
    paymentMethod: 'Payment Method',
    card: 'Card',
    upi: 'UPI',
    netbanking: 'Netbanking',
    cardDescription: 'Secure credit/debit card payment processing.',
    upiDescription: 'Pay using any UPI app like Google Pay, PhonePe, etc.',
    netbankingDescription: 'Pay directly from your bank account.',
    personalInformation: 'Personal Information',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    emailAddress: 'Email Address',
    enterEmail: 'Enter your email',
    phoneNumber: 'Phone Number',
    enterPhone: 'Enter your phone number',
    panNumber: 'PAN Number (for tax benefits)',
    enterPanNumber: 'Enter PAN number for 80G certificate',
    address: 'Address',
    enterAddress: 'Enter your address',
    messageOptional: 'Message (Optional)',
    shareWhyDonate: 'Share why you\'re making this donation',
    agreeTerms: 'I agree to the {termsLink} and {privacyLink}',
    termsAndConditions: 'terms and conditions',
    privacyPolicy: 'privacy policy',
    keepMeUpdated: 'Keep me updated about how my donation is making an impact',
    processing: 'Processing...',
    donateButton: 'Donate ₹{amount}',
    requiredFieldsMissing: 'Required Fields Missing',
    pleaseFillRequiredFields: 'Please fill in all required fields.',
    termsAgreementRequired: 'Terms Agreement Required',
    pleaseAgreeTerms: 'Please agree to the terms and conditions.',
    processingDonation: 'Processing Donation',
    pleaseWaitProcessing: 'Please wait while we process your donation...',
    donationSuccessful: 'Donation Successful!',
    thankYouDonation: 'Thank you for your donation of ₹{amount}. Transaction ID: {transactionId}',
    donationFailed: 'Donation Failed',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    invalidDonationAmount: 'Invalid donation amount',
    whyDonate: 'Why Donate to Samarthanam',
    whyDonateEducation: 'Support education for visually impaired students',
    whyDonateSkill: 'Provide skill development training to persons with disabilities',
    whyDonateSports: 'Enable sports opportunities for para-athletes',
    whyDonateLivelihood: 'Create livelihood opportunities through our programs',
    whyDonateTax: 'Tax benefits under Section 80G',
    yourImpact: 'Your Impact',
    impact1000Title: '₹1,000 can provide',
    impact1000: 'One month of educational support for a child',
    impact5000Title: '₹5,000 can provide',
    impact5000: 'Training materials for skill development',
    impact10000Title: '₹10,000 can provide',
    impact10000: 'Assistive technology for multiple students',
    needHelp: 'Need Help?',
    needHelpDescription: 'For any assistance with your donation, please contact us:',
    ourSupporters: 'Our Supporters',
    supportersDescription: 'Join these organizations in supporting our mission to create an inclusive world',
    supporterLogo: 'Supporter Logo',
    eventImageAlt: 'Event: {title}',
    aboutThisEvent: 'About This Event',
    close: 'Close',
    // Categories (you can add more as needed based on your actual event categories)
    'category.education': 'Education',
    'category.skill': 'Skill Development',
    'category.livelihood': 'Livelihood',
    'category.sports': 'Sports',
    'category.cultural': 'Cultural Programs',
    'category.general': 'General',
    joinUsTitle: 'Join Our Volunteer Community',
    joinUsSubtitle: 'Make a difference in the lives of visually impaired, disabled, and underprivileged individuals by becoming a part of our supportive community.',
    existingVolunteer: 'Existing Volunteer',
    existingVolunteerDescription: 'Already registered? Log in to your account to access your dashboard, view upcoming events, and manage your profile.',
    existingVolunteerFeature1: 'Access your personalized volunteer dashboard',
    existingVolunteerFeature2: 'Sign up for upcoming volunteer opportunities',
    existingVolunteerFeature3: 'Track your volunteer hours and contributions',
    logIn: 'Log In',
    newVolunteer: 'New Volunteer',
    newVolunteerDescription: 'Ready to make a difference? Register as a volunteer and start your journey with Samarthanam Trust.',
    newVolunteerFeature1: 'Create your volunteer profile with skills and interests',
    newVolunteerFeature2: 'Get matched with opportunities that suit your preferences',
    newVolunteerFeature3: 'Join a community of like-minded individuals making an impact',
    register: 'Register',
    volunteerLogin: 'Volunteer Login',
    loginSubtitle: 'Sign in to access your volunteer dashboard',
    email: 'Email',
    emailPlaceholder: 'volunteer@example.com',
    password: 'Password',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot Password?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    adminLogin: 'Admin Login',
    adminLoginNote: 'Administrators must log in separately through the Admin Login page',
    loginSuccessTitle: 'Login successful',
    loginSuccessDescription: 'Welcome back!',
    loginFailedTitle: 'Login failed',
    somethingWentWrong: 'Something went wrong',
    voiceInput: 'Voice Input',
    voiceInputDescription: 'Speak to enter text in the field',
    transcribedText: 'Transcribed Text:',
    done: 'Done',
    accessibilityOptions: 'Accessibility options',
    accessibility: 'Accessibility',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    enableHighContrast: 'Enable High Contrast',
    disableHighContrast: 'Disable High Contrast',
    enableTalkBack: 'Enable Talk Back',
    disableTalkBack: 'Disable Talk Back',
    enableVoiceInput: 'Enable Voice Input',
    disableVoiceInput: 'Disable Voice Input',
    increaseTextSize: 'Increase Text Size',
    decreaseTextSize: 'Decrease Text Size',
    resetTextSize: 'Reset Text Size'
  },
  hi: {
    home: 'होम',
    events: 'इवेंट्स',
    about: 'हमारे बारे में',
    donate: 'दान करें',
    volunteer: 'स्वयंसेवक',
    dashboard: 'डैशबोर्ड',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    toggleHighContrast: 'हाई कॉन्ट्रास्ट टॉगल करें',
    toggleLargerText: 'बड़ा टेक्स्ट टॉगल करें',
    language: 'भाषा',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    kannada: 'कन्नड़',
    upcomingEvents: 'आगामी कार्यक्रम',
    loadingEvents: 'कार्यक्रम लोड हो रहे हैं...',
    failedToLoadEvents: 'कार्यक्रम लोड करने में विफल। कृपया बाद में पुनः प्रयास करें।',
    showMore: 'और दिखाएं',
    livesImpacted: 'प्रभावित जीवन',
    eventsOrganized: 'आयोजित कार्यक्रम',
    volunteersEngaged: 'स्वयंसेवक संलग्न',
    yearsOfService: 'सेवा के वर्ष',
    aboutUs: 'हमारे बारे में',
    breakingBarriers: 'समावेशी विकास के लिए बाधाओं को तोड़ना',
    aboutDescription1: '1997 में स्थापित, समर्थनम ट्रस्ट शिक्षा, आजीविका, खेल, पुनर्वास और सांस्कृतिक गतिविधियों में विभिन्न पहलों के माध्यम से विकलांग व्यक्तियों को सशक्त बनाने में सबसे आगे रहा है।',
    aboutDescription2: 'हमारा प्रौद्योगिकी-संचालित दृष्टिकोण यह सुनिश्चित करता है कि हम व्यक्तियों को बाधाओं को पार करने और उनकी पूरी क्षमता हासिल करने में मदद करने के लिए सही उपकरण और संसाधन प्रदान कर सकें।',
    learnMore: 'हमारे बारे में और जानें',
    communityActivitiesAlt: 'समर्थनम ट्रस्ट समुदाय गतिविधियाँ',
    heroTitle: 'समावेशी प्रौद्योगिकी के माध्यम से जीवन को सशक्त बनाना',
    heroSubtitle: 'सुलभता, शिक्षा और समुदाय के माध्यम से दृष्टिबाधित, अक्षम और वंचित व्यक्तियों का समर्थन करने के हमारे मिशन में समर्थनम ट्रस्ट के साथ शामिल हों।',
    becomeVolunteer: 'स्वयंसेवक बनें',
    browseEvents: 'कार्यक्रम ब्राउज़ करें',
    scrollDown: 'नीचे स्क्रॉल करें',
    footerDescription: 'प्रौद्योगिकी और समुदाय समर्थन के माध्यम से दृष्टिबाधित, अक्षम और वंचित व्यक्तियों को सशक्त बनाना।',
    facebook: 'फेसबुक',
    twitter: 'ट्विटर',
    instagram: 'इंस्टाग्राम',
    youtube: 'यूट्यूब',
    quickLinks: 'त्वरित लिंक',
    contact: 'संपर्क',
    address: 'सीए साइट नंबर 1, 7वीं मेन, 7वीं क्रॉस, तीसरा चरण, जेपी नगर, बेंगलुरु, कर्नाटक 560078',
    stayUpdated: 'अद्यतन रहें',
    newsletterDescription: 'ईवेंट, स्वयंसेवक अवसरों और अधिक के अपडेट के लिए हमारे न्यूज़लेटर की सदस्यता लें।',
    yourEmail: 'आपका ईमेल',
    subscribe: 'सदस्यता लें',
    enterValidEmail: 'कृपया एक मान्य ईमेल पता दर्ज करें।',
    subscriptionFailed: 'सदस्यता विफल हुई। बाद में पुनः प्रयास करें।',
    subscribedSuccessfully: 'सफलतापूर्वक सदस्यता ली गई!',
    copyright: '© {{year}} समर्थनम ट्रस्ट फॉर द डिसएबल्ड। सर्वाधिकार सुरक्षित।',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    recommended: 'अनुशंसित',
    alreadySignedUp: 'पहले से साइन अप किया हुआ',
    signingUp: 'साइन अप हो रहा है...',
    volunteerForEvent: 'ईवेंट के लिए स्वयंसेवक',
    registerAsParticipant: 'प्रतिभागी के रूप में पंजीकरण करें',
    aboutTitle: 'समर्थनम ट्रस्ट के बारे में',
    aboutSubtitle: '1997 में स्थापित, समर्थनम ट्रस्ट शिक्षा, रोजगार और समावेशन के माध्यम से अक्षम लोगों को सशक्त बनाने के लिए समर्पित रहा है।',
    ourPurpose: 'हमारा उद्देश्य',
    missionVision: 'मिशन और विजन',
    missionVisionDescription: 'हम एक ऐसी दुनिया की कल्पना करते हैं जहां सभी अक्षम व्यक्तियों को शिक्षा, रोजगार और सामाजिक समावेशन के समान अवसर प्राप्त हों, जिससे वे गरिमा और स्वतंत्रता के साथ जीवन जी सकें।',
    education: 'शिक्षा',
    educationDescription: 'अक्षम लोगों और वंचित पृष्ठभूमि से आने वाले लोगों को गुणवत्तापूर्ण शिक्षा और प्रशिक्षण प्रदान करना।',
    employment: 'रोजगार',
    employmentDescription: 'कौशल विकास और उद्योगों के साथ साझेदारी के माध्यम से सार्थक रोजगार के अवसर बनाना।',
    inclusion: 'समावेशन',
    inclusionDescription: 'समाज के सभी पहलुओं में समावेशन को बढ़ावा देना, सभी व्यक्तियों के लिए समान भागीदारी सुनिश्चित करना।',
    awareness: 'जागरूकता',
    awarenessDescription: 'अक्षमताओं के बारे में जन जागरूकता बढ़ाना और सहायक नीतियों और बुनियादी ढांचे की वकालत करना।',
    ourJourney: 'हमारी यात्रा',
    milestonesAchievements: 'मील के पत्थर और उपलब्धियाँ',
    milestonesDescription: 'हमारी साधारण शुरुआत से लेकर वर्तमान प्रभाव तक, हम सभी के लिए एक अधिक समावेशी दुनिया बनाने की अपनी प्रतिबद्धता से प्रेरित रहे हैं।',
    foundation: 'स्थापना',
    foundationDescription: 'समर्थनम ट्रस्ट की स्थापना अक्षम व्यक्तियों और वंचित पृष्ठभूमि से आने वाले लोगों को सहायता प्रदान करने के दृष्टिकोण के साथ की गई थी।',
    educationCenter: 'शिक्षा केंद्र',
    educationCenterDescription: 'सुलभ बुनियादी ढांचे और शिक्षण सामग्री के साथ हमारा पहला समर्पित शिक्षा केंद्र स्थापित किया।',
    digitalAccess: 'डिजिटल पहुँच',
    digitalAccessDescription: 'दृष्टिबाधित व्यक्तियों के लिए विशेष रूप से डिज़ाइन किए गए डिजिटल साक्षरता कार्यक्रम शुरू किए।',
    nationalExpansion: 'राष्ट्रीय विस्तार',
    nationalExpansionDescription: 'भारत भर में पांच राज्यों में संचालन का विस्तार किया, जिससे हजारों और लाभार्थियों तक पहुँच बनी।',
    globalRecognition: 'वैश्विक मान्यता',
    globalRecognitionDescription: 'अक्षमता समावेशन और पहुंच नवाचार में हमारे काम के लिए अंतरराष्ट्रीय मान्यता प्राप्त हुई।',
    present: 'वर्तमान',
    embracingTechnology: 'प्रौद्योगिकी को अपनाना',
    embracingTechnologyDescription: 'अधिक सुलभ समाधान बनाने और व्यापक समुदायों तक पहुँचने के लिए उन्नत प्रौद्योगिकी का लाभ उठाना।',
    ourImpact: 'हमारा प्रभाव',
    makingDifference: 'फर्क डालना',
    impactDescription: 'हमारे काम ने देश भर में हजारों लोगों के जीवन को प्रभावित किया है, जिससे अक्षम व्यक्तियों और उनके समुदायों के लिए स्थायी सकारात्मक बदलाव आया है।',
    communityImpactAlt: 'समर्थनम समुदाय प्रभाव',
    empoweringLives: 'जीवन को सशक्त बनाना',
    empoweringLivesDescription: 'हमने 20,000 से अधिक अक्षम व्यक्तियों को शिक्षा और कौशल विकास प्रदान किया है, जिससे उन्हें स्वतंत्रता और गरिमा प्राप्त करने में मदद मिली है।',
    creatingOpportunities: 'अवसर पैदा करना',
    creatingOpportunitiesDescription: '200 से अधिक कंपनियों के साथ हमारी साझेदारी ने विविध क्षेत्रों में अक्षम व्यक्तियों के लिए हजारों रोजगार के अवसर बनाए हैं।',
    communityEngagement: 'समुदाय संलग्नता',
    communityEngagementDescription: '500 से अधिक आयोजनों और कार्यशालाओं के माध्यम से, हमने अक्षमता समावेशन के बारे में जागरूकता बढ़ाई है और देश भर में सहायक समुदाय बनाए हैं।',
    recognition: 'मान्यता',
    recognitionDescription: 'हमारे काम को अक्षमता सशक्तिकरण और समावेशन में उत्कृष्टता के लिए कई राष्ट्रीय और अंतरराष्ट्रीय पुरस्कारों से मान्यता मिली है।',
    ourTeam: 'हमारी टीम',
    leadership: 'नेतृत्व',
    leadershipDescription: 'एक अधिक समावेशी दुनिया बनाने के लिए समर्थनम के मिशन का नेतृत्व करने वाली समर्पित टीम से मिलें।',
    mahanteshName: 'महंतेश जी किवदासन्नवर',
    mahanteshPosition: 'संस्थापक और प्रबंध ट्रस्टी',
    supriyaName: 'सुप्रिया पुरवार',
    supriyaPosition: 'कार्यकारी निदेशक',
    rameshName: 'रमेश कुमार',
    rameshPosition: 'कार्यक्रम निदेशक',
    priyaName: 'प्रिया शर्मा',
    priyaPosition: 'प्रौद्योगिकी अधिकारी',
    donationTitle: 'समर्थनम ट्रस्ट को दान करें',
    donationSubtitle: 'आपका योगदान हमें शिक्षा, कौशल विकास और समावेशी कार्यक्रमों के माध्यम से अक्षम व्यक्तियों को सशक्त बनाने में मदद करता है।',
    taxExemptionInfo: 'समर्थनम ट्रस्ट को सभी दान भारत में धारा 80G के तहत कर छूट के लिए पात्र हैं।',
    donationDetails: 'आपके दान का विवरण',
    donationDetailsDescription: 'अपना दान पूरा करने के लिए कृपया विवरण भरें',
    donationType: 'दान का प्रकार',
    oneTimeDonation: 'एकमुश्त दान',
    monthlyDonation: 'मासिक दान',
    oneTimeDonationDescription: 'हमारे कार्यक्रमों का समर्थन करने के लिए एकमुश्त दान करें।',
    monthlyDonationDescription: 'आपका मासिक दान हमें अपने कार्यक्रमों की योजना बनाने और बनाए रखने में मदद करता है।',
    donationAmount: 'दान राशि (₹)',
    custom: 'कस्टम',
    enterAmount: 'राशि दर्ज करें',
    enterAmountPlaceholder: 'राशि दर्ज करें',
    donationPurpose: 'दान का उद्देश्य चुनें',
    donationEducation: 'शिक्षा',
    donationSkill: 'कौशल विकास',
    donationLivelihood: 'आजीविका',
    donationSports: 'खेल',
    donationCultural: 'सांस्कृतिक कार्यक्रम',
    donationGeneral: 'सामान्य दान',
    paymentMethod: 'भुगतान विधि',
    card: 'कार्ड',
    upi: 'यूपीआई',
    netbanking: 'नेटबैंकिंग',
    cardDescription: 'सुरक्षित क्रेडिट/डेबिट कार्ड भुगतान प्रसंस्करण।',
    upiDescription: 'Google Pay, PhonePe आदि जैसे किसी भी UPI ऐप का उपयोग करके भुगतान करें।',
    netbankingDescription: 'अपने बैंक खाते से सीधे भुगतान करें।',
    personalInformation: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    emailAddress: 'ईमेल पता',
    enterEmail: 'अपना ईमेल दर्ज करें',
    phoneNumber: 'फोन नंबर',
    enterPhone: 'अपना फोन नंबर दर्ज करें',
    panNumber: 'पैन नंबर (कर लाभ के लिए)',
    enterPanNumber: '80G प्रमाणपत्र के लिए पैन नंबर दर्ज करें',
    address: 'पता',
    enterAddress: 'अपना पता दर्ज करें',
    messageOptional: 'संदेश (वैकल्पिक)',
    shareWhyDonate: 'आप यह दान क्यों कर रहे हैं, इसे साझा करें',
    agreeTerms: 'मैं {termsLink} और {privacyLink} से सहमत हूँ',
    termsAndConditions: 'नियम और शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    keepMeUpdated: 'मुझे मेरे दान के प्रभाव के बारे में अपडेट रखें',
    processing: 'प्रसंस्करण...',
    donateButton: '₹{amount} दान करें',
    requiredFieldsMissing: 'आवश्यक क्षेत्र गायब हैं',
    pleaseFillRequiredFields: 'कृपया सभी आवश्यक क्षेत्रों को भरें।',
    termsAgreementRequired: 'नियमों से सहमति आवश्यक',
    pleaseAgreeTerms: 'कृपया नियमों और शर्तों से सहमत हों।',
    processingDonation: 'दान प्रसंस्करण',
    pleaseWaitProcessing: 'कृपया प्रतीक्षा करें जब तक हम आपके दान को संसाधित करते हैं...',
    donationSuccessful: 'दान सफल!',
    thankYouDonation: '₹{amount} के आपके दान के लिए धन्यवाद। लेनदेन आईडी: {transactionId}',
    donationFailed: 'दान विफल',
    unexpectedError: 'एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।',
    invalidDonationAmount: 'अमान्य दान राशि',
    whyDonate: 'समर्थनम को दान क्यों करें',
    whyDonateEducation: 'दृष्टिबाधित छात्रों के लिए शिक्षा का समर्थन करें',
    whyDonateSkill: 'अक्षम व्यक्तियों को कौशल विकास प्रशिक्षण प्रदान करें',
    whyDonateSports: 'पैराथलीटों के लिए खेल के अवसर सक्षम करें',
    whyDonateLivelihood: 'हमारे कार्यक्रमों के माध्यम से आजीविका के अवसर बनाएं',
    whyDonateTax: 'धारा 80G के तहत कर लाभ',
    yourImpact: 'आपका प्रभाव',
    impact1000Title: '₹1,000 प्रदान कर सकता है',
    impact1000: 'एक बच्चे के लिए एक महीने का शैक्षिक समर्थन',
    impact5000Title: '₹5,000 प्रदान कर सकता है',
    impact5000: 'कौशल विकास के लिए प्रशिक्षण सामग्री',
    impact10000Title: '₹10,000 प्रदान कर सकता है',
    impact10000: 'कई छात्रों के लिए सहायक तकनीक',
    needHelp: 'मदद चाहिए?',
    needHelpDescription: 'अपने दान के साथ किसी भी सहायता के लिए, कृपया हमसे संपर्क करें:',
    ourSupporters: 'हमारे समर्थक',
    supportersDescription: 'एक समावेशी दुनिया बनाने के हमारे मिशन का समर्थन करने में इन संगठनों में शामिल हों',
    supporterLogo: 'समर्थक लोगो',
    eventImageAlt: 'आयोजन: {title}',
    aboutThisEvent: 'इस आयोजन के बारे में',
    close: 'बंद करें',
    'category.education': 'शिक्षा',
    'category.skill': 'कौशल विकास',
    'category.livelihood': 'आजीविका',
    'category.sports': 'खेल',
    'category.cultural': 'सांस्कृतिक कार्यक्रम',
    'category.general': 'सामान्य',
    joinUsTitle: 'हमारे स्वयंसेवक समुदाय में शामिल हों',
    joinUsSubtitle: 'दृष्टिबाधित, अक्षम और वंचित व्यक्तियों के जीवन में बदलाव लाएं, हमारे सहायक समुदाय का हिस्सा बनकर।',
    existingVolunteer: 'मौजूदा स्वयंसेवक',
    existingVolunteerDescription: 'पहले से पंजीकृत हैं? अपने खाते में लॉग इन करें ताकि आप अपने डैशबोर्ड तक पहुंच सकें, आगामी आयोजनों को देख सकें और अपने प्रोफाइल को प्रबंधित कर सकें।',
    existingVolunteerFeature1: 'अपने व्यक्तिगत स्वयंसेवक डैशबोर्ड तक पहुंचें',
    existingVolunteerFeature2: 'आगामी स्वयंसेवक अवसरों के लिए साइन अप करें',
    existingVolunteerFeature3: 'अपने स्वयंसेवक घंटों और योगदान को ट्रैक करें',
    logIn: 'लॉग इन',
    newVolunteer: 'नया स्वयंसेवक',
    newVolunteerDescription: 'बदलाव लाने के लिए तैयार हैं? स्वयंसेवक के रूप में पंजीकरण करें और समर्थनम ट्रस्ट के साथ अपनी यात्रा शुरू करें।',
    newVolunteerFeature1: 'अपनी कौशल और रुचियों के साथ स्वयंसेवक प्रोफाइल बनाएं',
    newVolunteerFeature2: 'अपनी पसंद के अनुरूप अवसरों से मिलान प्राप्त करें',
    newVolunteerFeature3: 'प्रभाव डालने वाले समान विचारधारा वाले व्यक्तियों के समुदाय में शामिल हों',
    register: 'पंजीकरण',
    volunteerLogin: 'स्वयंसेवक लॉगिन',
    loginSubtitle: 'अपने स्वयंसेवक डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    email: 'ईमेल',
    emailPlaceholder: 'volunteer@example.com',
    password: 'पासवर्ड',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'पासवर्ड भूल गए?',
    signingIn: 'साइन इन हो रहा है...',
    signIn: 'साइन इन',
    noAccount: 'खाता नहीं है?',
    registerHere: 'यहां पंजीकरण करें',
    adminLogin: 'प्रशासक लॉगिन',
    adminLoginNote: 'प्रशासकों को प्रशासक लॉगिन पेज के माध्यम से अलग से लॉग इन करना होगा',
    loginSuccessTitle: 'लॉगिन सफल',
    loginSuccessDescription: 'वापस स्वागत है!',
    loginFailedTitle: 'लॉगिन विफल',
    somethingWentWrong: 'कुछ गलत हो गया',
    voiceInput: 'आवाज इनपुट',
    voiceInputDescription: 'क्षेत्र में पाठ दर्ज करने के लिए बोलें',
    transcribedText: 'प्रतिलिखित पाठ:',
    done: 'हो गया',
    accessibilityOptions: 'सुलभता विकल्प',
    accessibility: 'सुलभता',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    enableHighContrast: 'उच्च कंट्रास्ट सक्षम करें',
    disableHighContrast: 'उच्च कंट्रास्ट अक्षम करें',
    enableTalkBack: 'टॉक बैक सक्षम करें',
    disableTalkBack: 'टॉक बैक अक्षम करें',
    enableVoiceInput: 'आवाज इनपुट सक्षम करें',
    disableVoiceInput: 'आवाज इनपुट अक्षम करें',
    increaseTextSize: 'पाठ का आकार बढ़ाएं',
    decreaseTextSize: 'पाठ का आकार घटाएं',
    resetTextSize: 'पाठ का आकार रीसेट करें'
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    events: 'ಇವೆಂಟ್ಗಳು',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    donate: 'ದಾನ ಮಾಡಿ',
    volunteer: 'ಸ್ವಯಂಸೇವಕ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    toggleHighContrast: 'ಹೈ ಕಾಂಟ್ರಾಸ್ಟ್ ಟಾಗಲ್ ಮಾಡಿ',
    toggleLargerText: 'ದೊಡ್ಡ ಪಠ್ಯವನ್ನು ಟಾಗಲ್ ಮಾಡಿ',
    language: 'ಭಾಷೆ',
    english: 'ಇಂಗ್ಲಿಷ್',
    hindi: 'ಹಿಂದಿ',
    kannada: 'ಕನ್ನಡ',
    upcomingEvents: 'ಮುಂಬರುವ ಈವೆಂಟ್‌ಗಳು',
    loadingEvents: 'ಈವೆಂಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    failedToLoadEvents: 'ಈವೆಂಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    showMore: 'ಇನ್ನಷ್ಟು ತೋರಿಸು',
    livesImpacted: 'ಪ್ರಭಾವಿತ ಜೀವನಗಳು',
    eventsOrganized: 'ಆಯೋಜಿಸಲಾದ ಈವೆಂಟ್‌ಗಳು',
    volunteersEngaged: 'ಸ್ವಯಂಸೇವಕರು ತೊಡಗಿಸಿಕೊಂಡಿದ್ದಾರೆ',
    yearsOfService: 'ಸೇವೆಯ ವರ್ಷಗಳು',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    breakingBarriers: 'ಒಳಗೊಳ್ಳುವ ಬೆಳವಣಿಗೆಗಾಗಿ ತಡೆಗಳನ್ನು ಮುರಿಯುವುದು',
    aboutDescription1: '1997 ರಲ್ಲಿ ಸ್ಥಾಪನೆಯಾದ ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಶಿಕ್ಷಣ, ಜೀವನೋಪಾಯ, ಕ್ರೀಡೆ, ಪುನರ್ವಸತಿ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಚಟುವಟಿಕೆಗಳಲ್ಲಿ ವಿವಿಧ ಉಪಕ್ರಮಗಳ ಮೂಲಕ ಅಂಗವಿಕಲರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವಲ್ಲಿ ಮುಂಚೂಣಿಯಲ್ಲಿದೆ.',
    aboutDescription2: 'ನಮ್ಮ ತಂತ್ರಜ್ಞಾನ-ಚಾಲಿತ ವಿಧಾನವು ವ್ಯಕ್ತಿಗಳು ತಡೆಗಳನ್ನು ಮೀರಿ ತಮ್ಮ ಪೂರ್ಣ ಸಾಮರ್ಥ್ಯವನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡಲು ಸರಿಯಾದ ಉಪಕರಣಗಳು ಮತ್ತು ಸಂಪನ್ಮೂಲಗಳನ್ನು ಒದಗಿಸಬಹುದೆಂದು ಖಚಿತಪಡಿಸುತ್ತದೆ.',
    learnMore: 'ನಮ್ಮ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    communityActivitiesAlt: 'ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಸಮುದಾಯ ಚಟುವಟಿಕೆಗಳು',
    heroTitle: 'ಒಳಗೊಳ್ಳುವ ತಂತ್ರಜ್ಞಾನದ ಮೂಲಕ ಜೀವನಗಳನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು',
    heroSubtitle: 'ಪ್ರವೇಶಸಾಧ್ಯತೆ, ಶಿಕ್ಷಣ ಮತ್ತು ಸಮುದಾಯದ ಮೂಲಕ ದೃಷ್ಟಿದೋಷ, ಅಂಗವೈಕಲ್ಯ ಮತ್ತು ವಂಚಿತ ವ್ಯಕ್ತಿಗಳನ್ನು ಬೆಂಬಲಿಸುವ ನಮ್ಮ ಧ್ಯೇಯದಲ್ಲಿ ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ.',
    becomeVolunteer: 'ಸ್ವಯಂಸೇವಕರಾಗಿ',
    browseEvents: 'ಈವೆಂಟ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    scrollDown: 'ಕೆಳಗೆ ಸ್ಕ್ರೋಲ್ ಮಾಡಿ',
    footerDescription: 'ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಸಮುದಾಯ ಬೆಂಬಲದ ಮೂಲಕ ದೃಷ್ಟಿದೋಷ, ಅಂಗವೈಕಲ್ಯ ಮತ್ತು ವಂಚಿತ ವ್ಯಕ್ತಿಗಳನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು.',
    facebook: 'ಫೇಸ್‌ಬುಕ್',
    twitter: 'ಟ್ವಿಟರ್',
    instagram: 'ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್',
    youtube: 'ಯೂಟ್ಯೂಬ್',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    contact: 'ಸಂಪರ್ಕ',
    address: 'ಸಿಎ ಸೈಟ್ ಸಂಖ್ಯೆ 1, 7ನೇ ಮೇನ್, 7ನೇ ಕ್ರಾಸ್, 3ನೇ ಹಂತ, ಜೆಪಿ ನಗರ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ 560078',
    stayUpdated: 'ಅಪ್‌ಡೇಟ್ ಆಗಿರಿ',
    newsletterDescription: 'ಈವೆಂಟ್‌ಗಳು, ಸ್ವಯಂಸೇವಕ ಅವಕಾಶಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು ತಾಜಾ ಮಾಹಿತಿಗಾಗಿ ನಮ್ಮ ಸುದ್ದಿಪತ್ರಕ್ಕೆ ಚಂದಾದಾರರಾಗಿ.',
    yourEmail: 'ನಿಮ್ಮ ಇಮೇಲ್',
    subscribe: 'ಚಂದಾದಾರರಾಗಿ',
    enterValidEmail: 'ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.',
    subscriptionFailed: 'ಚಂದಾದಾರಿಕೆ ವಿಫಲವಾಗಿದೆ. ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    subscribedSuccessfully: 'ಯಶಸ್ವಿಯಾಗಿ ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ!',
    copyright: '© {{year}} ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಫಾರ್ ದಿ ಡಿಸೇಬಲ್ಡ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    recommended: 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    alreadySignedUp: 'ಈಗಾಗಲೇ ಸೈನ್ ಅಪ್ ಆಗಿದೆ',
    signingUp: 'ಸೈನ್ ಅಪ್ ಆಗುತ್ತಿದೆ...',
    volunteerForEvent: 'ಈವೆಂಟ್‌ಗೆ ಸ್ವಯಂಸೇವಕ',
    registerAsParticipant: 'ಪಾಲ್ಗೊಳ್ಳುವವರಾಗಿ ನೋಂದಾಯಿಸಿ',
    aboutTitle: 'ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಬಗ್ಗೆ',
    aboutSubtitle: '1997 ರಲ್ಲಿ ಸ್ಥಾಪಿತವಾದ ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಶಿಕ್ಷಣ, ಉದ್ಯೋಗ ಮತ್ತು ಸಮಾವೇಶದ ಮೂಲಕ ಅಂಗವಿಕಲರನ್ನು ಸಶಕ್ತಗೊಳಿಸಲು ಸಮರ್ಪಿಸಲಾಗಿದೆ.',
    ourPurpose: 'ನಮ್ಮ ಉದ್ದೇಶ',
    missionVision: 'ಮಿಷನ್ ಮತ್ತು ದೃಷ್ಟಿ',
    missionVisionDescription: 'ಎಲ್ಲಾ ಅಂಗವಿಕಲ ವ್ಯಕ್ತಿಗಳಿಗೆ ಶಿಕ್ಷಣ, ಉದ್ಯೋಗ ಮತ್ತು ಸಾಮಾಜಿಕ ಸಮಾವೇಶಕ್ಕೆ ಸಮಾನ ಅವಕಾಶಗಳು ಲಭ್ಯವಾಗುವ ಒಂದು ಜಗತ್ತನ್ನು ನಾವು ಊಹಿಸುತ್ತೇವೆ, ಅವರಿಗೆ ಘನತೆ ಮತ್ತು ಸ್ವಾತಂತ್ರ್ಯದೊಂದಿಗೆ ಜೀವನ ನಡೆಸಲು ಸಾಧ್ಯವಾಗುತ್ತದೆ.',
    education: 'ಶಿಕ್ಷಣ',
    educationDescription: 'ಅಂಗವಿಕಲರಿಗೆ ಮತ್ತು ವಂಚಿತ ಹಿನ್ನೆಲೆಯಿಂದ ಬಂದವರಿಗೆ ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ ಒದಗಿಸುವುದು.',
    employment: 'ಉದ್ಯೋಗ',
    employmentDescription: 'ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಕೈಗಾರಿಕೆಗಳೊಂದಿಗಿನ ಪಾಲುದಾರಿಕೆಯ ಮೂಲಕ ಅರ್ಥಪೂರ್ಣ ಉದ್ಯೋಗ ಅವಕಾಶಗಳನ್ನು ಸೃಷ್ಟಿಸುವುದು.',
    inclusion: 'ಸಮಾವೇಶ',
    inclusionDescription: 'ಸಮಾಜದ ಎಲ್ಲಾ ಅಂಶಗಳಲ್ಲಿ ಸಮಾವೇಶವನ್ನು ಉತ್ತೇಜಿಸುವುದು, ಎಲ್ಲಾ ವ್ಯಕ್ತಿಗಳಿಗೆ ಸಮಾನ ಭಾಗವಹಿಸುವಿಕೆಯನ್ನು ಖಚಿತಪಡಿಸುವುದು.',
    awareness: 'ಜಾಗೃತಿ',
    awarenessDescription: 'ಅಂಗವಿಕಲತೆಯ ಬಗ್ಗೆ ಸಾರ್ವಜನಿಕ ಜಾಗೃತಿಯನ್ನು ಹೆಚ್ಚಿಸುವುದು ಮತ್ತು ಬೆಂಬಲ ನೀತಿಗಳು ಮತ್ತು ಮೂಲಸೌಕರ್ಯಕ್ಕಾಗಿ ವಕಾಲತ್ತು ಮಾಡುವುದು.',
    ourJourney: 'ನಮ್ಮ ಪಯಣ',
    milestonesAchievements: 'ಮೈಲಿಗಲ್ಲುಗಳು ಮತ್ತು ಸಾಧನೆಗಳು',
    milestonesDescription: 'ನಮ್ಮ ಸರಳ ಆರಂಭದಿಂದ ಈಗಿನ ಪ್ರಭಾವದವರೆಗೆ, ಎಲ್ಲರಿಗೂ ಹೆಚ್ಚು ಸಮಾವೇಶಕ ಜಗತ್ತನ್ನು ಸೃಷ್ಟಿಸುವ ನಮ್ಮ ಬದ್ಧತೆಯಿಂದ ನಾವು ಪ್ರೇರಿತರಾಗಿದ್ದೇವೆ.',
    foundation: 'ಸ್ಥಾಪನೆ',
    foundationDescription: 'ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್ ಅಂಗವಿಕಲ ವ್ಯಕ್ತಿಗಳಿಗೆ ಮತ್ತು ವಂಚಿತ ಹಿನ್ನೆಲೆಯಿಂದ ಬಂದವರಿಗೆ ಸಹಾಯ ಒದಗಿಸುವ ದೃಷ್ಟಿಯೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಯಿತು.',
    educationCenter: 'ಶಿಕ್ಷಣ ಕೇಂದ್ರ',
    educationCenterDescription: 'ಪ್ರವೇಶಿಸಬಹುದಾದ ಮೂಲಸೌಕರ್ಯ ಮತ್ತು ಕಲಿಕೆ ಸಾಮಗ್ರಿಗಳೊಂದಿಗೆ ನಮ್ಮ ಮೊದಲ ಸಮರ್ಪಿತ ಶಿಕ್ಷಣ ಕೇಂದ್ರವನ್ನು ಸ್ಥಾಪಿಸಿದೆವು.',
    digitalAccess: 'ಡಿಜಿಟಲ್ ಪ್ರವೇಶ',
    digitalAccessDescription: 'ದೃಷ್ಟಿಬाधित ವ್ಯಕ್ತಿಗಳಿಗೆ ವಿಶೇಷವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಡಿಜಿಟಲ್ ಸಾಕ್ಷರತೆ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿದೆವು.',
    nationalExpansion: 'ರಾಷ್ಟ್ರೀಯ ವಿಸ್ತರಣೆ',
    nationalExpansionDescription: 'ಭಾರತದಾದ್ಯಂತ ಐದು ರಾಜ್ಯಗಳಿಗೆ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ವಿಸ್ತರಿಸಿದೆವು, ಇದರಿಂದ ಸಾವಿರಾರು ಫಲಾನುಭವಿಗಳಿಗೆ ತಲುಪಿದೆವು.',
    globalRecognition: 'ವೈಶ್ವಿಕ ಮನ್ನಣೆ',
    globalRecognitionDescription: 'ಅಂಗವಿಕಲತೆ ಸಮಾವೇಶ ಮತ್ತು ಪ್ರವೇಶ ನಾವೀನ್ಯತೆಯಲ್ಲಿ ನಮ್ಮ ಕೆಲಸಕ್ಕಾಗಿ ಅಂತರರಾಷ್ಟ್ರೀಯ ಮನ್ನಣೆ ಪಡೆದಿದ್ದೇವೆ.',
    present: 'ಪ್ರಸ್ತುತ',
    embracingTechnology: 'ತಂತ್ರಜ್ಞಾನವನ್ನು ಅಳವಡಿಸಿಕೊಳ್ಳುವುದು',
    embracingTechnologyDescription: 'ಹೆಚ್ಚು ಪ್ರವೇಶಿಸಬಹುದಾದ ಪರಿಹಾರಗಳನ್ನು ಸೃಷ್ಟಿಸಲು ಮತ್ತು ವಿಶಾಲ ಸಮುದಾಯಗಳಿಗೆ ತಲುಪಲು ಸುಧಾರಿತ ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸಿಕೊಳ್ಳುವುದು.',
    ourImpact: 'ನಮ್ಮ ಪ್ರಭಾವ',
    makingDifference: 'ವ್ಯತ್ಯಾಸ ಮಾಡುವುದು',
    impactDescription: 'ನಮ್ಮ ಕೆಲಸವು ದೇಶಾದ್ಯಂತ ಸಾವಿರಾರು ಜೀವನಗಳನ್ನು ಸ್ಪರ್ಶಿಸಿದೆ, ಅಂಗವಿಕಲ ವ್ಯಕ್ತಿಗಳಿಗೆ ಮತ್ತು ಅವರ ಸಮುದಾಯಗಳಿಗೆ ಶಾಶ್ವತ ಸಕಾರಾತ್ಮಕ ಬದಲಾವಣೆಯನ್ನು ತಂದಿದೆ.',
    communityImpactAlt: 'ಸಮರ್ಥನಂ ಸಮುದಾಯ ಪ್ರಭಾವ',
    empoweringLives: 'ಜೀವನಗಳನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು',
    empoweringLivesDescription: 'ನಾವು 20,000 ಕ್ಕೂ ಹೆಚ್ಚು ಅಂಗವಿಕಲ ವ್ಯಕ್ತಿಗಳಿಗೆ ಶಿಕ್ಷಣ ಮತ್ತು ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿಯನ್ನು ಒದಗಿಸಿದ್ದೇವೆ, ಅವರಿಗೆ ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಘನತೆಯನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡಿದ್ದೇವೆ.',
    creatingOpportunities: 'ಅವಕಾಶಗಳನ್ನು ಸೃಷ್ಟಿಸುವುದು',
    creatingOpportunitiesDescription: '200 ಕ್ಕೂ ಹೆಚ್ಚು ಕಂಪನಿಗಳೊಂದಿಗಿನ ನಮ್ಮ ಪಾಲುದಾರಿಕೆಯು ವಿವಿಧ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಅಂಗವಿಕಲ ವ್ಯಕ್ತಿಗಳಿಗೆ ಸಾವಿರಾರು ಉದ್ಯೋಗ ಅವಕಾಶಗಳನ್ನು ಸೃಷ್ಟಿಸಿದೆ.',
    communityEngagement: 'ಸಮುದಾಯ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ',
    communityEngagementDescription: '500 ಕ್ಕೂ ಹೆಚ್ಚು ಈವೆಂಟ್‌ಗಳು ಮತ್ತು ಕಾರ್ಯಾಗಾರಗಳ ಮೂಲಕ, ನಾವು ಅಂಗವಿಕಲತೆ ಸಮಾವೇಶದ ಬಗ್ಗೆ ಜಾಗೃತಿಯನ್ನು ಮೂಡಿಸಿದ್ದೇವೆ ಮತ್ತು ದೇಶಾದ್ಯಂತ ಬೆಂಬಲ ಸಮುದಾಯಗಳನ್ನು ನಿರ್ಮಿಸಿದ್ದೇವೆ.',
    recognition: 'ಮನ್ನಣೆ',
    recognitionDescription: 'ನಮ್ಮ ಕೆಲಸವು ಅಂಗವಿಕಲತೆ ಸಶಕ್ತೀಕರಣ ಮತ್ತು ಸಮಾವೇಶದಲ್ಲಿ ಉತ್ಕೃಷ್ಟತೆಗಾಗಿ ಹಲವಾರು ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಶಸ್ತಿಗಳೊಂದಿಗೆ ಮನ್ನಣೆ ಪಡೆದಿದೆ.',
    ourTeam: 'ನಮ್ಮ ತಂಡ',
    leadership: 'ನಾಯಕತ್ವ',
    leadershipDescription: 'ಹೆಚ್ಚು ಸಮಾವೇಶಕ ಜಗತ್ತನ್ನು ಸೃಷ್ಟಿಸುವ ಸಮರ್ಥನಂನ ಮಿಷನ್‌ಗೆ ನಾಯಕತ್ವ ವಹಿಸುವ ಸಮರ್ಪಿತ ತಂಡವನ್ನು ಭೇಟಿಯಾಗಿ.',
    mahanteshName: 'ಮಹಂತೇಶ್ ಜಿ ಕಿವದಾಸನ್ನವರ್',
    mahanteshPosition: 'ಸಂಸ್ಥಾಪಕ ಮತ್ತು ವ್ಯವಸ್ಥಾಪಕ ಟ್ರಸ್ಟಿ',
    supriyaName: 'ಸುಪ್ರಿಯಾ ಪುರ್ವಾರ್',
    supriyaPosition: 'ಕಾರ್ಯನಿರ್ವಾಹಕ ನಿರ್ದೇಶಕ',
    rameshName: 'ರಮೇಶ್ ಕುಮಾರ್',
    rameshPosition: 'ಕಾರ್ಯಕ್ರಮಗಳ ನಿರ್ದೇಶಕ',
    priyaName: 'ಪ್ರಿಯಾ ಶರ್ಮಾ',
    priyaPosition: 'ತಂತ್ರಜ್ಞಾನ ಅಧಿಕಾರಿ',
    donationTitle: 'ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್‌ಗೆ ದಾನ ಮಾಡಿ',
    donationSubtitle: 'ನಿಮ್ಮ ಕೊಡುಗೆಯು ಶಿಕ್ಷಣ, ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಸಮಾವೇಶಕ ಕಾರ್ಯಕ್ರಮಗಳ ಮೂಲಕ ಅಂಗವಿಕಲರನ್ನು ಸಶಕ್ತಗೊಳಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    taxExemptionInfo: 'ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್‌ಗೆ ಎಲ್ಲಾ ದಾನಗಳು ಭಾರತದಲ್ಲಿ ಸೆಕ್ಷನ್ 80G ಅಡಿಯಲ್ಲಿ ತೆರಿಗೆ ವಿನಾಯಿತಿಗೆ ಅರ್ಹವಾಗಿವೆ.',
    donationDetails: 'ನಿಮ್ಮ ದಾನದ ವಿವರಗಳು',
    donationDetailsDescription: 'ನಿಮ್ಮ ದಾನವನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ದಯವಿಟ್ಟು ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
    donationType: 'ದಾನದ ಪ್ರಕಾರ',
    oneTimeDonation: 'ಒಂದು ಬಾರಿಗೆ ದಾನ',
    monthlyDonation: 'ಮಾಸಿಕ ದಾನ',
    oneTimeDonationDescription: 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಬೆಂಬಲಿಸಲು ಒಂದು ಬಾರಿಗೆ ದಾನ ಮಾಡಿ.',
    monthlyDonationDescription: 'ನಿಮ್ಮ ಮಾಸಿಕ ದಾನವು ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಯೋಜಿಸಲು ಮತ್ತು ನಿರ್ವಹಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    donationAmount: 'ದಾನದ ಮೊತ್ತ (₹)',
    custom: 'ಕಸ್ಟಮ್',
    enterAmount: 'ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ',
    enterAmountPlaceholder: 'ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ',
    donationPurpose: 'ದಾನದ ಉದ್ದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    donationEducation: 'ಶಿಕ್ಷಣ',
    donationSkill: 'ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ',
    donationLivelihood: 'ಜೀವನೋಪಾಯ',
    donationSports: 'ಕ್ರೀಡೆ',
    donationCultural: 'ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು',
    donationGeneral: 'ಸಾಮಾನ್ಯ ದಾನ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ',
    card: 'ಕಾರ್ಡ್',
    upi: 'ಯುಪಿಐ',
    netbanking: 'ನೆಟ್‌ಬ್ಯಾಂಕಿಂಗ್',
    cardDescription: 'ಸುರಕ್ಷಿತ ಕ್ರೆಡಿಟ್/ಡೆಬಿಟ್ ಕಾರ್ಡ್ ಪಾವತಿ ಸಂಸ್ಕರಣೆ.',
    upiDescription: 'Google Pay, PhonePe ಮುಂತಾದ ಯಾವುದೇ UPI ಆಪ್ ಬಳಸಿ ಪಾವತಿಸಿ.',
    netbankingDescription: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯಿಂದ ನೇರವಾಗಿ ಪಾವತಿಸಿ.',
    personalInformation: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    enterFullName: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    enterEmail: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    enterPhone: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    panNumber: 'ಪ್ಯಾನ್ ಸಂಖ್ಯೆ (ತೆರಿಗೆ ಪ್ರಯೋಜನಗಳಿಗಾಗಿ)',
    enterPanNumber: '80G ಪ್ರಮಾಣಪತ್ರಕ್ಕಾಗಿ ಪ್ಯಾನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    address: 'ವಿಳಾಸ',
    enterAddress: 'ನಿಮ್ಮ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    messageOptional: 'ಸಂದೇಶ (ಐಚ್ಛಿಕ)',
    shareWhyDonate: 'ನೀವು ಈ ದಾನವನ್ನು ಏಕೆ ಮಾಡುತ್ತಿದ್ದೀರಿ ಎಂಬುದನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    agreeTerms: 'ನಾನು {termsLink} ಮತ್ತು {privacyLink} ಗೆ ಸಮ್ಮತಿಸುತ್ತೇನೆ',
    termsAndConditions: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    keepMeUpdated: 'ನನ್ನ ದಾನದ ಪ್ರಭಾವದ ಬಗ್ಗೆ ನನ್ನನ್ನು ತಾಜಾ ಮಾಹಿತಿಯಲ್ಲಿ ಇರಿಸಿ',
    processing: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    donateButton: '₹{amount} ದಾನ ಮಾಡಿ',
    requiredFieldsMissing: 'ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳು ಕಾಣೆಯಾಗಿವೆ',
    pleaseFillRequiredFields: 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.',
    termsAgreementRequired: 'ನಿಯಮಗಳ ಸಮ್ಮತಿ ಅಗತ್ಯ',
    pleaseAgreeTerms: 'ದಯವಿಟ್ಟು ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳಿಗೆ ಸಮ್ಮತಿಸಿ.',
    processingDonation: 'ದಾನವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ',
    pleaseWaitProcessing: 'ನಿಮ್ಮ ದಾನವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವವರೆಗೆ ದಯವಿಟ್ಟು ಕಾಯಿರಿ...',
    donationSuccessful: 'ದಾನ ಯಶಸ್ವಿ!',
    thankYouDonation: '₹{amount} ನಿಮ್ಮ ದಾನಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ಲೆನದೆನ ಐಡಿ: {transactionId}',
    donationFailed: 'ದಾನ ವಿಫಲವಾಗಿದೆ',
    unexpectedError: 'ಅನಿರೀಕ್ಷಿತ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    invalidDonationAmount: 'ಅಮಾನ್ಯ ದಾನದ ಮೊತ್ತ',
    whyDonate: 'ಸಮರ್ಥನಂಗೆ ದಾನ ಏಕೆ ಮಾಡಬೇಕು',
    whyDonateEducation: 'ದೃಷ್ಟಿದೋಷವುಳ್ಳ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶಿಕ್ಷಣವನ್ನು ಬೆಂಬಲಿಸಿ',
    whyDonateSkill: 'ಅಂಗವಿಕಲರಿಗೆ ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ತರಬೇತಿಯನ್ನು ಒದಗಿಸಿ',
    whyDonateSports: 'ಪ್ಯಾರಾಅಥ್ಲೀಟ್‌ಗಳಿಗೆ ಕ್ರೀಡಾ ಅವಕಾಶಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    whyDonateLivelihood: 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳ ಮೂಲಕ ಜೀವನೋಪಾಯದ ಅವಕಾಶಗಳನ್ನು ಸೃಷ್ಟಿಸಿ',
    whyDonateTax: 'ಸೆಕ್ಷನ್ 80G ಅಡಿಯಲ್ಲಿ ತೆರಿಗೆ ಪ್ರಯೋಜನಗಳು',
    yourImpact: 'ನಿಮ್ಮ ಪ್ರಭಾವ',
    impact1000Title: '₹1,000 ಒದಗಿಸಬಹುದು',
    impact1000: 'ಒಬ್ಬ ಮಗುವಿಗೆ ಒಂದು ತಿಂಗಳ ಶೈಕ್ಷಣಿಕ ಬೆಂಬಲ',
    impact5000Title: '₹5,000 ಒದಗಿಸಬಹುದು',
    impact5000: 'ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿಗಾಗಿ ತರಬೇತಿ ಸಾಮಗ್ರಿಗಳು',
    impact10000Title: '₹10,000 ಒದಗಿಸಬಹುದು',
    impact10000: 'ಹಲವಾರು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಸಹಾಯಕ ತಂತ್ರಜ್ಞಾನ',
    needHelp: 'ಸಹಾಯ ಬೇಕೇ?',
    needHelpDescription: 'ನಿಮ್ಮ ದಾನದೊಂದಿಗೆ ಯಾವುದೇ ಸಹಾಯಕ್ಕಾಗಿ, ದಯವಿಟ್ಟು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ:',
    ourSupporters: 'ನಮ್ಮ ಬೆಂಬಲಿಗರು',
    supportersDescription: 'ಸಮಾವೇಶಕ ಜಗತ್ತನ್ನು ಸೃಷ್ಟಿಸುವ ನಮ್ಮ ಧ್ಯೇಯವನ್ನು ಬೆಂಬಲಿಸುವಲ್ಲಿ ಈ ಸಂಸ್ಥೆಗಳಲ್ಲಿ ಸೇರಿಕೊಳ್ಳಿ',
    supporterLogo: 'ಬೆಂಬಲಿಗರ ಲೋಗೋ',
    eventImageAlt: 'ಈವೆಂಟ್: {title}',
    aboutThisEvent: 'ಈ ಈವೆಂಟ್ ಬಗ್ಗೆ',
    close: 'ಮುಚ್ಚಿ',
    'category.education': 'ಶಿಕ್ಷಣ',
    'category.skill': 'ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ',
    'category.livelihood': 'ಜೀವನೋಪಾಯ',
    'category.sports': 'ಕ್ರೀಡೆ',
    'category.cultural': 'ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು',
    'category.general': 'ಸಾಮಾನ್ಯ',
    joinUsTitle: 'ನಮ್ಮ ಸ್ವಯಂಸೇವಕ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
    joinUsSubtitle: 'ದೃಷ್ಟಿದೋಷವುಳ್ಳ, ಅಂಗವಿಕಲ ಮತ್ತು ವಂಚಿತ ವ್ಯಕ್ತಿಗಳ ಜೀವನದಲ್ಲಿ ವ್ಯತ್ಯಾಸವನ್ನು ಮಾಡಿ, ನಮ್ಮ ಬೆಂಬಲ ಸಮುದಾಯದ ಭಾಗವಾಗಿ.',
    existingVolunteer: 'ಈಗಾಗಲೇ ಇರುವ ಸ್ವಯಂಸೇವಕ',
    existingVolunteerDescription: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ? ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ, ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅನ್ನು ಪ್ರವೇಶಿಸಲು, ಮುಂಬರುವ ಈವೆಂಟ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಮತ್ತು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ನಿರ್ವಹಿಸಲು.',
    existingVolunteerFeature1: 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಸ್ವಯಂಸೇವಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅನ್ನು ಪ್ರವೇಶಿಸಿ',
    existingVolunteerFeature2: 'ಮುಂಬರುವ ಸ್ವಯಂಸೇವಕ ಅವಕಾಶಗಳಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    existingVolunteerFeature3: 'ನಿಮ್ಮ ಸ್ವಯಂಸೇವಕ ಗಂಟೆಗಳು ಮತ್ತು ಕೊಡುಗೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    logIn: 'ಲಾಗ್ ಇನ್',
    newVolunteer: 'ಹೊಸ ಸ್ವಯಂಸೇವಕ',
    newVolunteerDescription: 'ವ್ಯತ್ಯಾಸವನ್ನು ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ? ಸ್ವಯಂಸೇವಕರಾಗಿ ನೋಂದಾಯಿಸಿ ಮತ್ತು ಸಮರ್ಥನಂ ಟ್ರಸ್ಟ್‌ನೊಂದಿಗೆ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ.',
    newVolunteerFeature1: 'ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು ಮತ್ತು ಆಸಕ್ತಿಗಳೊಂದಿಗೆ ಸ್ವಯಂಸೇವಕ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    newVolunteerFeature2: 'ನಿಮ್ಮ ಆದ್ಯತೆಗಳಿಗೆ ಸರಿಹೊಂದುವ ಅವಕಾಶಗಳೊಂದಿಗೆ ಹೊಂದಾಣಿಕೆ ಪಡೆಯಿರಿ',
    newVolunteerFeature3: 'ಪ್ರಭಾವ ಬೀರುವ ಒಂದೇ ಮನಸ್ಸಿನ ವ್ಯಕ್ತಿಗಳ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
    register: 'ನೋಂದಾಯಿಸಿ',
    volunteerLogin: 'ಸ್ವಯಂಸೇವಕ ಲಾಗಿನ್',
    loginSubtitle: 'ನಿಮ್ಮ ಸ್ವಯಂಸೇವಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅನ್ನು ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    email: 'ಇಮೇಲ್',
    emailPlaceholder: 'volunteer@example.com',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತುಹೋಗಿದೆಯೇ?',
    signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    signIn: 'ಸೈನ್ ಇನ್',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    registerHere: 'ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ',
    adminLogin: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    adminLoginNote: 'ನಿರ್ವಾಹಕರು ಪ್ರತ್ಯೇಕವಾಗಿ ನಿರ್ವಾಹಕ ಲಾಗಿನ್ ಪುಟದ ಮೂಲಕ ಲಾಗ್ ಇನ್ ಮಾಡಬೇಕು',
    loginSuccessTitle: 'ಲಾಗಿನ್ ಯಶಸ್ವಿ',
    loginSuccessDescription: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    loginFailedTitle: 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
    somethingWentWrong: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    voiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    voiceInputDescription: 'ಕ್ಷೇತ್ರದಲ್ಲಿ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಲು ಮಾತನಾಡಿ',
    transcribedText: 'ಪ್ರತಿಲಿಖಿತ ಪಠ್ಯ:',
    done: 'ಮುಗಿದಿದೆ',
    accessibilityOptions: 'ಪ್ರವೇಶಿಸುವಿಕೆ ಆಯ್ಕೆಗಳು',
    accessibility: 'ಪ್ರವೇಶಿಸುವಿಕೆ',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    enableHighContrast: 'ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್ ಸಕ್ರಿಯಗೊಳಿಸಿ',
    disableHighContrast: 'ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    enableTalkBack: 'ಟಾಕ್ ಬ್ಯಾಕ್ ಸಕ್ರಿಯಗೊಳಿಸಿ',
    disableTalkBack: 'ಟಾಕ್ ಬ್ಯಾಕ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    enableVoiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಸಕ್ರಿಯಗೊಳಿಸಿ',
    disableVoiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    increaseTextSize: 'ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಹೆಚ್ಚಿಸಿ',
    decreaseTextSize: 'ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಕಡಿಮೆ ಮಾಡಿ',
    resetTextSize: 'ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಮರುಹೊಂದಿಸಿ'
  }
};

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};